# 服务端口配置
server:
  port: 8081  # 项目启动端口号

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  # 全局 JSON 日期格式
    time-zone: GMT+8                  # 设置时区为中国标准时间
  data:
    redis:
      # Redis 主机地址
      host: 139.224.133.80
      # Redis 主机端口
      # port: 6060
      port: 6379
      # Redis 主机密码
      password: question0.
      # 连接的库索引
      database: 0
      lettuce:
        pool:
          max-active: 100    # 最大并发连接数
          max-idle: 50       # 最大空闲连接数
          min-idle: 10       # 最小空闲连接数
  datasource:
    url: jdbc:mysql://139.224.133.80:3306/petSystem?characterEncoding=utf-8&serverTimezone=Asia/Shanghai  # 数据库连接 URL
    username: root             # 数据库用户名
    password: ${DB_PASSWORD}   # 数据库密码，建议从环境变量读取
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC 驱动类
    hikari:
      minimum-idle: 3          # 最小空闲连接数
      maximum-pool-size: 10    # 最大连接池数量
      max-lifetime: 1800000    # 连接最大存活时间（单位：毫秒，30分钟）
      connection-timeout: 10000      # 获取连接的最大等待时间（单位：毫秒）
      idle-timeout: 600000           # 空闲连接最大存活时间（单位：毫秒）
      connection-test-query: SELECT 1  # 测试连接的 SQL 语句，用于验证连接是否有效

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 日志到控制台（开发环境建议开启）
    map-underscore-to-camel-case: true  # 开启数据库字段自动下划线转驼峰映射

  global-config:
    db-config:
      logic-delete-field: delFlag       # 全局逻辑删除字段名（与实体类字段对应）
      logic-delete-value: 1             # 被逻辑删除时的值
      logic-not-delete-value: 0         # 未被逻辑删除时的值
      id-type: auto                     # 主键生成策略（数据库自增）

  mapper-locations: classpath*:mapper/**/*.xml  # 指定 Mapper XML 文件路径，支持多模块扫描

